/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ProductModel: {
      pplConfirmAge15?: boolean | null;
      pplConfirmAge18?: boolean | null;
      pplDisabledParcelBox?: boolean | null;
      pplDisabledAlzaBox?: boolean;
      pplDisabledParcelShop?: boolean | null;
      pplDisabledTransport?: string[] | null;
      pplSizes?: components["schemas"]["PackageSizeModel"][] | null;
    };
    CategoryModel: {
      pplConfirmAge15?: boolean | null;
      pplConfirmAge18?: boolean | null;
      pplDisabledParcelBox?: boolean | null;
      pplDisabledAlzaBox?: boolean;
      pplDisabledParcelShop?: boolean | null;
      pplDisabledTransport?: string[] | null;
      pplSize?: components["schemas"]["PackageSizeModel"];
    };
    PackageSizeModel: {
      xSize?: number | null;
      ySize?: number | null;
      zSize?: number | null;
    };
    ParcelDataModel: {
      name?: string | null;
      activeCardPayment?: boolean | null;
      activeCashPayment?: boolean | null;
      code?: string | null;
      country?: string | null;
      openHours?: string[] | null;
      street?: string | null;
      city?: string | null;
      zipCode?: string | null;
      id?: number | null;
      rnd?: number | null;
      accessPointType?: string | null;
      gps?: ({
        latitude?: number | null;
        longitude?: number | null;
      }) | null;
    };
    GlobalSettingModel: {
      useOrderNumberInPackages?: boolean;
      useOrderNumberInVariableSymbol?: boolean;
    };
    ParcelPlacesModel: {
      disabledByStripe?: boolean | null;
      disabledParcelBox?: boolean | null;
      disabledAlzaBox?: boolean | null;
      disabledParcelShop?: boolean | null;
      disabledCountries?: string[] | null;
      mapLanguage?: string | null;
    };
    MyApi2: {
      client_id: string | null;
      client_secret: string | null;
    };
    WhisperSettingModel: {
      active: boolean | null;
      url?: string | null;
    };
    WhisperAddressModel: {
      city?: string | null;
      zipCode?: string | null;
      street?: string | null;
      houseNumber?: string | null;
      evidenceNumber?: string | null;
    };
    UpdateShipmentModel: {
      referenceId: string | null;
      codVariableNumber?: string | null;
      codValue?: number | null;
      codValueCurrency?: string | null;
      codBankAccountId?: number | null;
      senderId?: number | null;
      serviceCode: string | null;
      orderId?: number | null;
      hasParcel?: boolean | null;
      parcelId?: number | null;
      age?: string | null;
      note?: string | null;
      packages: components["schemas"]["PackageModel"][] | null;
    };
    UpdateParcelModel: {
      parcelCode?: string | null;
    };
    UpdateShipmentSenderModel: {
      senderId: number | null;
    };
    UpdateShipmentParcelModel: {
      parcelCode: string | null;
      hasParcel?: boolean | null;
    };
    CreateShipmentLabelBatchModel: {
      printSetting: string | null;
      shipmentId: number[] | null;
    };
    ShipmentLabelRefreshBatchModel: {
      shipmentId: number[] | null;
    };
    ShipmentWithAdditionalModel: {
      shipment: components["schemas"]["ShipmentModel"];
      errors?: components["schemas"]["WpErrorModel"][] | null;
    };
    WpErrorModel: {
      key: string;
      values: string[];
    };
    BatchModel: {
      id: number;
      remoteBatchId?: string | null;
      name?: string | null;
      created: string;
      lock?: boolean;
    };
    PrepareShipmentBatchModel: {
      items: components["schemas"]["PrepareShipmentBatchItemModel"][] | null;
    };
    PrepareShipmentBatchItemModel: {
      orderId?: number | null;
      shipmentId?: number | null;
    };
    PrepareShipmentBatchReturnModel: {
      shipmentId?: number[] | null;
    };
    RefreshShipmentBatchReturnModel: {
      batchs?: string[] | null;
      shipments?: components["schemas"]["ShipmentModel"][] | null;
    };
    PackageModel: {
      id?: number | null;
      shipmentNumber?: string | null;
      referenceId?: string | null;
      labelId?: string | null;
      importError?: string | null;
      importErrorCode?: string | null;
      weight?: number | null;
      insurance?: number | null;
      insuranceCurrency?: string | null;
      phase?: string | null;
      phaseLabel?: string | null;
      lastUpdatePhase?: string | null;
      ignorePhase?: boolean | null;
    };
    ParcelAddressModel: {
      id?: number | null;
      code?: string | null;
      name?: string | null;
      name2?: string | null;
      street?: string | null;
      city?: string | null;
      zip?: string | null;
      country?: string | null;
      remoteId?: string | null;
      type?: string | null;
      lat?: number | null;
      lng?: number | null;
    };
    LabelPrintModel: {
      title: string;
      code: string;
    };
    CollectionAddressModel: {
      street: string | null;
      city: string | null;
      zip: string | null;
      country: string | null;
      code?: string | null;
      name?: string | null;
      default?: boolean | null;
    };
    SenderAddressModel: {
      id?: number | null;
      addressName: string | null;
      name: string | null;
      contact?: string | null;
      street: string | null;
      city: string | null;
      zip: string | null;
      country: string | null;
      mail?: string | null;
      phone?: string | null;
      note?: string | null;
    };
    RecipientAddressModel: {
      contact?: string | null;
      name: string | null;
      street: string | null;
      city: string | null;
      zip: string | null;
      country: string | null;
      mail?: string | null;
      phone?: string | null;
    };
    CartModel: {
      isPriceWithDph?: boolean | null;
      parcelRequired?: boolean | null;
      parcelBoxEnabled?: boolean | null;
      parcelShopEnabled?: boolean | null;
      alzaBoxEnabled?: boolean | null;
      mapEnabled?: boolean | null;
      disabledByWeight?: boolean | null;
      disabledByRules?: boolean | null;
      disabledByCountry?: boolean;
      disabledBySize?: boolean | null;
      enabledParcelCountries?: string[] | null;
      ageRequired?: boolean | null;
      codPayment?: string | null;
      serviceCode?: string;
      disablePayments?: string[] | null;
      disabledByProduct?: boolean;
      disableCod?: boolean | null;
      codFee?: number | null;
      codFeeDPH?: components["schemas"]["CalculatedDPH"];
      cost?: number | null;
      costDPH?: components["schemas"]["CalculatedDPH"];
      taxableName?: string | null;
    };
    ShipmentModel: {
      id?: number | null;
      packages?: components["schemas"]["PackageModel"][] | null;
      printState?: string | null;
      /** @enum {string|null} */
      importState?: "None" | "Accepted" | "InProcess" | "Complete" | "Error" | null;
      referenceId?: string | null;
      note?: string | null;
      codValue?: number | null;
      codValueCurrency?: string | null;
      codVariableNumber?: string | null;
      serviceCode?: string | null;
      serviceName?: string | null;
      batchId?: string | null;
      batchRemoteId?: string | null;
      hasParcel?: boolean | null;
      orderId?: number | null;
      parcel?: components["schemas"]["ParcelAddressModel"];
      recipient?: components["schemas"]["RecipientAddressModel"];
      sender?: components["schemas"]["SenderAddressModel"];
      age?: string | null;
      lock?: boolean | null;
      importErrors?: string[] | null;
      /** @enum {string|null} */
      phase?: "Undelivered" | "Delivered" | "PickedUpFromSender" | "DeliveredToPickupPoint" | "OutForDelivery" | "NotDelivered" | "CodPaidDate" | "BackToSender" | "Rejected" | "DataShipment" | "Active" | "Canceled" | "Dormant" | null;
    };
    CurrencyModel: {
      code: string;
      title: string;
    };
    ShipmentPhaseModel: {
      code: string;
      title: string;
      watch: boolean;
      orderState: string | null;
    };
    SyncPhasesModel: {
      maxSync: number | null;
      phases: components["schemas"]["ShipmentPhaseModel"][] | null;
    };
    UpdateSyncPhasesModel: {
      maxSync?: number | null;
      phases?: (({
          code: string | null;
          watch: boolean | null;
          orderState?: string | null;
        })[]) | null;
    };
    OrderStatusModel: {
      code: string;
      title: string;
    };
    CountryModel: {
      code: string;
      title: string;
      parcelAllowed: boolean;
      codAllowed: string[];
    };
    ShipmentMethodModel: {
      code: string;
      title: string;
      description: string;
      ageValidation: boolean | null;
      codAvailable: boolean;
      parcelRequired: boolean;
      disabledParcelTypes?: string[] | null;
      availableParcelTypes?: string[] | null;
      countries: string[];
      maxWeight: number | null;
      maxDimension?: number[] | null;
      maxPackages: number | null;
    };
    NewCollectionModel: {
      sendDate: string;
      contact?: string | null;
      estimatedShipmentCount?: number | null;
      telephone?: string | null;
      note?: string | null;
      email?: string | null;
    };
    CollectionModel: {
      id: number;
      remoteCollectionId?: string | null;
      referenceId: string;
      createdDate: string;
      sendDate: string;
      sendToApiDate?: string | null;
      /** @enum {string} */
      state?: "BeforeSend" | "None" | "Created" | "PickedUp" | "NotPickedUp" | "Canceled";
      estimatedShipmentCount?: number | null;
      shipmentCount: number;
      contact?: string | null;
      telephone?: string | null;
      note?: string | null;
      email?: string | null;
    };
    PrintSettingModel: {
      format?: string;
      orderStatuses?: string[];
    };
    ShipmentMethodSettingModel: {
      code: string;
      costByWeight?: boolean | null;
      parcelBoxes?: boolean | null;
      title?: string | null;
      description?: string | null;
      disablePayments?: string[];
      codPayment?: string | null;
      isPriceWithDph?: boolean | null;
      currencies: components["schemas"]["ShipmentMethodSettingCurrencyModel"][];
      weights: components["schemas"]["ShipmentMethodSettingWeightRuleModel"][];
      disabledParcelCountries?: string[] | null;
      disabledParcelBox?: boolean | null;
      disabledAlzaBox?: boolean | null;
      disabledParcelShop?: boolean | null;
    };
    ShipmentMethodSettingCurrencyModel: {
      enabled?: boolean | null;
      currency: string;
      costOrderFree?: number | null;
      costCodFee?: number | null;
      costCodFeeAlways?: boolean | null;
      costOrderFreeCod?: number | null;
      cost?: number | null;
    };
    ShipmentMethodSettingPriceRuleModel: {
      price?: number | null;
      currency: string;
    };
    ShipmentMethodSettingWeightRuleModel: {
      from?: number | null;
      to?: number | null;
      disabledParcelBox?: boolean | null;
      disabledAlzaBox?: boolean;
      disabledParcelShop?: boolean | null;
      prices: components["schemas"]["ShipmentMethodSettingPriceRuleModel"][];
    };
    ErrorLogItemModel: {
      id?: number;
      trace?: string;
    };
    ErrorLogProductSettingModel: {
      id?: number;
      categoryIds?: number[];
      name?: string;
      weight?: number | null;
      setting?: components["schemas"]["ProductModel"];
      parent?: number | null;
    };
    ErrorLogCategorySettingModel: {
      name?: string | null;
      id?: number;
      setting?: components["schemas"]["CategoryModel"];
      parent?: number | null;
    };
    ErrorLogShipmentSettingModel: {
      name?: string;
      shipmentSetting?: components["schemas"]["ShipmentMethodSettingModel"];
      rawBasicData?: string | null;
      rawWeightData?: string | null;
      zones?: string;
    };
    ErrorLogModel: {
      mail?: string | null;
      info?: string | null;
      shipmentsSetting?: components["schemas"]["ErrorLogShipmentSettingModel"][] | null;
      globalParcelSetting?: components["schemas"]["ParcelPlacesModel"];
      categorySetting?: components["schemas"]["ErrorLogCategorySettingModel"][];
      productsSetting?: components["schemas"]["ErrorLogProductSettingModel"][];
      orders?: unknown[];
      errors?: components["schemas"]["ErrorLogItemModel"][];
    };
    SendErrorLogModel: components["schemas"]["ErrorLogModel"] & ({
      message?: string | null;
    });
    CalculatedDPH: {
      dphId?: number;
      value?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
